/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking;

import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Jian
 */
public class Login extends javax.swing.JFrame {
// HashMap to store username-password pairs
    HashMap<String, String> credentials = new HashMap<>();
    
    // HashMap to store username-balance pairs
    HashMap<String, Double> balances = new HashMap<>();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jcshow_password = new javax.swing.JCheckBox();
        blogin = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        bexit = new javax.swing.JToggleButton();
        jtuser = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(204, 102, 0));
        jLabel2.setFont(new java.awt.Font("Impact", 2, 36)); // NOI18N
        jLabel2.setText("Point.BANK");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 90));
        jLabel2.setMinimumSize(new java.awt.Dimension(30, 26));
        jLabel2.setPreferredSize(new java.awt.Dimension(33, 16));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(280, 40, 190, 40);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setText("Email:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(130, 180, 50, 25);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setText("Password:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 240, 80, 25);

        jcshow_password.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jcshow_password.setText("Show password");
        jcshow_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcshow_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(jcshow_password);
        jcshow_password.setBounds(260, 270, 130, 30);

        blogin.setBackground(new java.awt.Color(204, 204, 204));
        blogin.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        blogin.setText("Login");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        jPanel2.add(blogin);
        blogin.setBounds(370, 300, 72, 27);

        jpassword.setBackground(new java.awt.Color(153, 153, 153));
        jpassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(jpassword);
        jpassword.setBounds(180, 234, 180, 26);

        bexit.setBackground(new java.awt.Color(204, 204, 204));
        bexit.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel2.add(bexit);
        bexit.setBounds(290, 300, 70, 27);

        jtuser.setBackground(new java.awt.Color(153, 153, 153));
        jtuser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuserActionPerformed(evt);
            }
        });
        jPanel2.add(jtuser);
        jtuser.setBounds(180, 174, 180, 26);

        Create.setBackground(new java.awt.Color(204, 204, 204));
        Create.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        Create.setText("Create Account");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        jPanel2.add(Create);
        Create.setBounds(50, 350, 130, 27);

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        jLabel5.setText("Welcome to");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 50, 190, 40);

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel6.setText("Log in to access your account ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 90, 250, 23);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 2, 12)); // NOI18N
        jLabel1.setText("Click this to register your account in our system:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 330, 300, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcshow_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcshow_passwordActionPerformed
        // Show password
        if(jcshow_password.isSelected()){
            jpassword.setEchoChar((char)0);
        }
        else{
            jpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jcshow_passwordActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String username = jtuser.getText();
        String password = new String(jpassword.getPassword());
        
        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, " Warning! Username or password cannot be empty. (CREATE ONE FIRST, if you dont have an account.)\n *JUST TYPE ANYTHING IN THE USERNAME & PASSWORD THEN PRESS CREATE ACCOUNT*\n *ACCOUNT WILL BE SAVED*");
            return;
        }
        
        // Check if username exists
        if (credentials.containsKey(username)) {
            // Check if password is correct
            if (credentials.get(username).equals(password)) {
                JOptionPane.showMessageDialog(null, "Login successful!");
                // Proceed to main application window or perform other actions
               Menu menuFrame = new Menu(username);
               menuFrame.setBalances(balances);
               menuFrame.setVisible(true);
               dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect password!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Account does not exist.(REGISTER FIRST!.)\n 1.JUST TYPE ANYTHING IN THE EMAIL & PASSWORD THEN PRESS CREATE ACCOUNT \n 2.ACCOUNT WILL BE REGISTERED \n 3.CLICK LOG IN AGAIN");
        }
                                            
    }                                      

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // Exit Button

        int result = JOptionPane.showConfirmDialog(null," Are you sure you want to exit? ", "Admin",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null , "DE GUZMAN, JIAN, B. ITE232");
            System.exit(0);
        }

    }//GEN-LAST:event_bexitActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String username = jtuser.getText();
        String password = new String(jpassword.getPassword());
        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username or password cannot be empty!");
            return;
        }       
        // Check if username already exists
        if (credentials.containsKey(username)) {
            JOptionPane.showMessageDialog(null, "Account is already existed, try another!");
        } else {
            // Add username-password pair to credentials
            credentials.put(username, password);
            // Set initial balance for the new account
            balances.put(username, 5000.0);
            JOptionPane.showMessageDialog(null, "Account created successfully!");
        }
    }//GEN-LAST:event_CreateActionPerformed

    private void jtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JToggleButton bexit;
    private javax.swing.JButton blogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcshow_password;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtuser;
    // End of variables declaration//GEN-END:variables
}
